export const productList = [
    {
      id: 1,
      name: 'Pomegranates',
      type: 'juices',
      oldPrice: '600',
      newPrice: '399',
      rating: '3',
      status: 'sale',
      inventory: '500',
      src1: '/img/pomegranates.jpg',
      src2: '/img/walnut.jpg'
    },
    {
      id: 2,
      name: 'Pineapple',
      type: 'fruits',
      oldPrice: 450,
      newPrice: 399,
      rating: 2.5,
      status: 'sale',
      inventory: 290,
      src1: '/img/pineapple.jpg',
      src2: '/img/pea.jpg'
    },
    {
      id: 3,
      name: 'Peach',
      type: 'juices',
      oldPrice: 300,
      newPrice: 250,
      rating: 5,
      status: 'sale',
      inventory: 320,
      src1: '/img/peace.jpg',
      src2: '/img/potato.jpg'
    },
    {
      id: 4,
      name: 'Potato',
      type: 'veggies',
      oldPrice: 350,
      newPrice: 300,
      rating: 4.5,
      status: 'hot',
      inventory: 220,
      src1: '/img/potato.jpg',
      src2: '/img/sweetpotato.jpg'
    },
    {
      id: 5,
      name: 'Bellpepper',
      type: 'veggies',
      oldPrice: 260,
      newPrice: 210,
      rating: 4.5,
      status: 'sale',
      inventory: 340,
      src1: '/img/bellpepper.jpg',
      src2: '/img/sweetpotato.jpg'
    },
    {
      id: 6,
      name: 'Redbellpepper',
      type: 'veggies',
      oldPrice: 349,
      newPrice: 349,
      rating: 4,
      status: 'soldout',
      inventory: 0,
      src1: '/img/redbellpepp.jpg',
      src2: '/img/basilbunch.jpg'
    },
    {
      id: 7,
      name: 'Cherry',
      type: 'juices',
      oldPrice: 70,
      newPrice: 70,
      rating: 5,
      status: 'soldout',
      inventory: 0,
      src1: '/img/cherry.jpg',
      src2: '/img/pea.jpg'
    },
    {
      id: 8,
      name: 'Spinach',
      type: 'veggies',
      oldPrice: 180,
      newPrice: 180,
      rating: 3,
      status: 'able',
      inventory: 130,
      src1: '/img/spinach.jpg',
      src2: '/img/potato.jpg'
    },
    {
      id: 9,
      name: 'Basilbunch',
      type: 'veggies',
      oldPrice: 349,
      newPrice: 349,
      rating: 4,
      status: 'able',
      inventory: 70,
      src1: '/img/basilbunch.jpg',
      src2: '/img/potato.jpg'
    },
    {
      id: 10,
      name: 'Pea',
      type: 'veggies',
      oldPrice: 220,
      newPrice: 220,
      rating: 3,
      status: 'hot',
      inventory: 79,
      src1: '/img/pea.jpg',
      src2: '/img/walnut.jpg'
    },
    {
      id: 11,
      name: 'Muhabbet',
      type: 'veggies',
      oldPrice: 70,
      newPrice: 70,
      rating: 4,
      status: 'soldout',
      inventory: 0,
      src1: '/img/muhabbet.jpg',
      src2: '/img/pea.jpg'
    },
    {
      id: 12,
      name: 'Persil',
      type: 'veggies',
      oldPrice: 200,
      newPrice: 200,
      rating: 4,
      status: 'able',
      inventory: 80,
      src1: '/img/persil.jpg',
      src2: '/img/basilbunch.jpg'
    },
    {
      id: 13,
      name: 'Watermelon',
      type: 'fruits',
      oldPrice: 180,
      newPrice: 180,
      rating: 3.5,
      status: 'able',
      inventory: 110,
      src1: '/img/watermelon.jpg',
      src2: '/img/potato.jpg'
    },
    {
      id: 14,
      name: 'Grape',
      type: 'fruits',
      oldPrice: 339,
      newPrice: 339,
      rating: 4,
      status: 'able',
      inventory: 40,
      src1: '/img/grape.jpg',
      src2: '/img/potato.jpg'
    },
    {
      id: 15,
      name: 'Sapota',
      type: 'fruits',
      oldPrice: 220,
      newPrice: 220,
      rating: 3,
      status: 'sale',
      inventory: 140,
      src1: '/img/sapota.jpg',
      src2: '/img/walnut.jpg'
    },
    {
      id: 16,
      name: 'Apple',
      type: 'fruits',
      oldPrice: 299,
      newPrice: 299,
      rating: 5,
      status: 'hot',
      inventory: 90,
      src1: '/img/apple.jpg',
      src2: '/img/stringbean.jpg'
    },
    {
      id: 17,
      name: 'Walnut',
      type: 'veggies',
      oldPrice: 270,
      newPrice: 270,
      rating: 3,
      status: 'able',
      inventory: 160,
      src1: '/img/walnut.jpg',
      src2: '/img/basilbunch.jpg'
    },
    {
      id: 18,
      name: 'Stringbean',
      type: 'veggies',
      oldPrice: 30,
      newPrice: 25,
      rating: 4,
      status: 'sale',
      inventory: 110,
      src1: '/img/stringbean.jpg',
      src2: '/img/pea.jpg'
    },
    {
      id: 19,
      name: 'Tomato',
      type: 'veggies',
      oldPrice: 450,
      newPrice: 399,
      rating: 5,
      status: 'sale',
      inventory: 350,
      src1: '/img/tomato.jpg',
      src2: '/img/lingonberry.jpg'
    },
    {
      id: 20,
      name: 'Orange',
      type: 'juices',
      oldPrice: 300,
      newPrice: 280,
      rating: 4.5,
      status: 'sale',
      inventory: 300,
      src1: '/img/orange.jpg',
      src2: '/img/cucumber.jpg'
    },
    {
      id: 21,
      name: 'SweetLime',
      type: 'juices',
      oldPrice: 200,
      newPrice: 180,
      rating: 3.5,
      status: 'sale',
      inventory: 250,
      src1: '/img/sweetlime.jpg',
      src2: '/img/potato.jpg'
    },
    {
      id: 22,
      name: 'Strawberry',
      type: 'juices',
      oldPrice: 340,
      newPrice: 300,
      rating: 4.5,
      status: 'sale',
      inventory: 190,
      src1: '/img/strawberry.jpg',
      src2: '/img/sweetpotato.jpg'
    },
    {
      id: 23,
      name: 'Papaya',
      type: 'fruits',
      oldPrice: 250,
      newPrice: 220,
      rating: 3,
      status: 'sale',
      inventory: 290,
      src1: '/img/papaya.jpg',
      src2: '/img/walnut.jpg'
    },
    {
      id: 24,
      name: 'Banana',
      type: 'juices',
      oldPrice: 400,
      newPrice: 349,
      rating: 4,
      status: 'hot',
      inventory: 100,
      src1: '/img/banana.jpg',
      src2: '/img/basilbunch.jpg'
    },
    {
      id: 25,
      name: 'Cabbage',
      type: 'veggies',
      oldPrice: 280,
      newPrice: 280,
      rating: 3,
      status: 'able',
      inventory: 180,
      src1: '/img/cabbage.jpg',
      src2: '/img/cucumber.jpg'
    },
    {
      id: 26,
      name: 'Lychee',
      type: 'fruits',
      oldPrice: 599,
      newPrice: 599,
      rating: 4.5,
      status: 'soldout',
      inventory: 0,
      src1: '/img/lychee.jpg',
      src2: '/img/papaya.jpg'
    },
    {
      id: 27,
      name: 'Carrot',
      type: 'juices',
      oldPrice: 150,
      newPrice: 150,
      rating: 3.5,
      status: 'able',
      inventory: 150,
      src1: '/img/carrot.jpg',
      src2: '/img/grape.jpg'
    },
    {
      id: 28,
      name: 'Ligonberry',
      type: 'fruits',
      oldPrice: 170,
      newPrice: 170,
      rating: 0,
      status: 'able',
      inventory: 100,
      src1: '/img/lingonberry.jpg',
      src2: '/img/watermelon.jpg'
    }
]